# Default Configuration for Julia Auction System
# This file contains all default values for the auction system
# Environment variables can override any value using the pattern: AUCTION_SECTION_KEY
# Example: AUCTION_PHANTOM_AUCTION_BID_PROBABILITY=0.4

[phantom_auction]
# Phantom auction configuration
bid_probability = 0.3               # Default bid generation probability
duration_ms = 100                   # Auction duration in milliseconds
min_improvement_bps = 10            # Minimum improvement in basis points (0.1%)
max_improvement_bps = 50            # Maximum improvement in basis points (0.5%)
reveal_delay_ms = 20                # Reveal phase delay in milliseconds
min_participants = 2                # Minimum number of participants required

[coordinator]
# Multi-party coordination settings
consensus_threshold = 0.67          # Consensus threshold (2/3 majority)
base_success_rate = 0.9            # Base success rate for operations
timeout_seconds = 30.0             # Timeout for coordination operations
retry_count = 3                     # Number of retry attempts
heartbeat_interval_seconds = 5.0    # Heartbeat interval for health monitoring
min_response_rate = 0.5            # Minimum participant response rate
heartbeat_timeout_multiplier = 3.0  # Allow 3 missed heartbeats before timeout

[settlement]
# Settlement system configuration
base_gas_cost = 100000             # Base gas cost for settlement operations
timeout_ms = 200.0                 # Settlement operation timeout
max_retries = 3                    # Maximum retry attempts
price_improvement_threshold_bps = 10  # Minimum price improvement required
max_batch_size = 50                # Maximum settlements per batch
fallback_enabled = true            # Enable fallback mechanisms
validation_slippage_tolerance = 0.02  # Slippage tolerance for validation (2%)
liquidity_tolerance = 0.05         # Liquidity tolerance (5%)
max_price_deviation = 0.05         # Maximum price deviation allowed (5%)
max_slippage_tolerance = 0.02      # Maximum slippage tolerance (2%)
gas_limit = 10000000               # Gas limit for settlement batches
execution_slippage_tolerance = 0.005  # Slippage tolerance for execution (0.5%)
execution_tolerance = 0.02         # Execution output tolerance (2%)
step_time_estimate_ms = 20.0       # Time estimate per execution step
settlement_time_estimate_ms = 5.0  # Time estimate per settlement

[circuit_breaker]
# Circuit breaker configuration for fault tolerance
failure_threshold = 5              # Number of failures to trip circuit
recovery_threshold = 3             # Successes needed in half-open to close
timeout_ms = 30000.0              # Time to wait before trying half-open (30 seconds)
slow_call_threshold_ms = 100.0     # Calls slower than this count as failures
half_open_max_calls = 10           # Max calls allowed in half-open state
volume_threshold = 10              # Minimum calls before circuit can trip
error_percentage_threshold = 50.0   # Percentage of errors to trip circuit
monitoring_window_ms = 60000.0     # Sliding window for error calculation (1 minute)

[timeouts]
# Timeout configurations for various operations
auction_timeout_ms = 50.0          # Fast auction processing
settlement_timeout_ms = 200.0      # Settlement operations
cfmm_bridge_timeout_ms = 100.0     # CFMM bridge calls
phantom_auction_timeout_ms = 30.0  # Phantom auction creation
default_operation_timeout_ms = 75.0 # Default for other operations
health_check_interval_ms = 30000.0  # Health check interval (30 seconds)
settlement_prepare_timeout_ms = 100.0  # Prepare phase timeout for settlements
settlement_commit_timeout_ms = 500.0   # Commit phase timeout for settlements

[retry]
# Retry configuration
max_retry_attempts = 2             # Limited retries for speed
base_retry_delay_ms = 10.0         # Very fast initial retry
max_retry_delay_ms = 100.0         # Cap retry delays
retry_jitter_ratio = 0.2           # Jitter ratio for retry delays

[performance]
# Performance monitoring and limits
p99_latency_target_ms = 10.0       # 99th percentile latency target
p95_latency_target_ms = 5.0        # 95th percentile latency target
max_acceptable_latency_ms = 100.0   # Hard latency limit
slow_operation_threshold_ms = 15.0  # Operations slower than this are flagged
memory_usage_threshold_percent = 75.0  # Memory usage alert threshold
cpu_usage_threshold_percent = 70.0     # CPU usage alert threshold
disk_usage_threshold_percent = 80.0    # Disk usage alert threshold

[resources]
# Resource limits and management
max_concurrent_auctions = 1000     # Maximum concurrent auctions
max_pending_settlements = 500      # Maximum pending settlements
max_memory_usage_mb = 4096         # Memory limit (4GB)
thread_pool_size = 8               # Thread pool size
max_records = 1000                 # Maximum records to keep in memory

[monitoring]
# Monitoring and alerting configuration
resource_monitor_interval_ms = 10000.0   # Resource monitoring interval (10 seconds)
performance_report_interval_ms = 60000.0  # Performance report interval (1 minute)
metrics_retention_hours = 72              # Metrics retention (3 days)
log_retention_days = 7                    # Log retention (1 week)
performance_data_retention_hours = 48     # Performance data retention (2 days)

[alerting]
# Alert thresholds and configuration
sla_violation_alert_threshold_percent = 5.0   # Alert if >5% violate SLA
error_rate_alert_threshold_percent = 1.0      # Alert if >1% error rate
consecutive_failures_alert_threshold = 3      # Alert after 3 consecutive failures

[simulation]
# Simulation and testing configuration
default_num_rounds = 1000          # Default number of simulation rounds
default_num_items = 1              # Default number of items per auction
min_valuation = 1.0                # Minimum valuation for bidders
max_valuation = 100.0              # Maximum valuation for bidders
default_reserve_price = 0.0        # Default reserve price
quick_test_rounds = 10             # Quick test configuration
stress_test_rounds = 10000         # Stress test configuration
stress_test_items = 5              # Items for stress testing
default_seed = 42                  # Default random seed
benchmark_rounds = 100             # Benchmark simulation rounds
valuation_step = 0.01              # Step size for valuation ranges

[bidding]
# Bidding strategy configuration
default_shading_factor = 0.1       # Default bid shading factor
noise_variance = 0.1               # Noise variance for bidding strategies
risk_aversion = 0.0                # Default risk aversion parameter
valuation_multiplier_min = 0.8     # Minimum valuation multiplier
valuation_multiplier_max = 1.2     # Maximum valuation multiplier
base_valuation = 50.0              # Base bidder valuation for testing
high_valuation = 75.0              # High bidder valuation for testing

[auction_mechanics]
# Core auction mechanism parameters
tie_breaking_default = "random"    # Default tie breaking method
second_price_safety_factor = 0.01  # Safety factor for second price calculations
bid_validation_timeout_ms = 5.0    # Timeout for bid validation
commitment_verification_enabled = true  # Enable commitment verification
price_weight = 0.8                 # Weight for price scoring in auctions
fee_weight = 0.2                   # Weight for fee scoring in auctions

[network]
# Network and communication configuration
connection_timeout_ms = 5000.0     # Network connection timeout
read_timeout_ms = 3000.0           # Network read timeout
max_connections = 100              # Maximum concurrent connections
keepalive_interval_ms = 30000.0    # Connection keepalive interval

[security]
# Security configuration
enable_commitment_hashing = true   # Enable commitment hash verification
max_bid_value_multiplier = 2.0     # Maximum bid value as multiplier of baseline
priority_fee_max_ratio = 0.01      # Maximum priority fee as ratio of volume
signature_verification_enabled = true  # Enable signature verification

[environment]
# Environment-specific settings (overridden by environment configs)
environment = "development"        # Current environment
debug_logging = true               # Enable debug logging
performance_logging = true         # Enable performance logging